services:
  bot:
    image: jendox/retention-bot:${IMAGE_TAG:-latest}
    network_mode: host
    env_file:
      - ./.env.prod
    environment:
      METRICS__HOST: 127.0.0.1
      METRICS__PORT: 8000
    command: ["python", "-m", "src.main"]
    restart: unless-stopped

  reminders:
    image: jendox/retention-bot:${IMAGE_TAG:-latest}
    network_mode: host
    env_file:
      - ./.env.prod
    environment:
      METRICS__HOST: 127.0.0.1
      METRICS__PORT: 8001
    command: ["python", "-m", "src.workers.reminders"]
    restart: unless-stopped

  payments:
    image: jendox/retention-bot:${IMAGE_TAG:-latest}
    network_mode: host
    env_file:
      - ./.env.prod
    environment:
      METRICS__HOST: 127.0.0.1
      METRICS__PORT: 8002
    command: ["python", "-m", "src.workers.payments"]
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:v2.54.1
    network_mode: host
    volumes:
      - ./prometheus.prod.yml:/etc/prometheus/prometheus.yml:ro
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--web.listen-address=127.0.0.1:9090"
    restart: unless-stopped

