"""

Revision ID: 8e97ddfe6b8f
Revises: 
Create Date: 2025-12-15 16:06:54.330755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8e97ddfe6b8f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('timezone', postgresql.ENUM('EUROPE_MINSK', 'EUROPE_MOSCOW', 'EUROPE_KIEV', 'EUROPE_WARSAW', 'EUROPE_VILNIUS', 'EUROPE_RIGA', 'EUROPE_TALLINN', 'EUROPE_BUCHAREST', 'EUROPE_CHISINAU', 'ASIA_YEREVAN', 'ASIA_TBILISI', 'ASIA_ALMATY', 'ASIA_BISHKEK', 'ASIA_TASHKENT', 'EUROPE_LONDON', 'EUROPE_PARIS', 'EUROPE_BERLIN', 'EUROPE_ROME', 'EUROPE_MADRID', 'EUROPE_AMSTERDAM', 'AMERICA_NEW_YORK', 'AMERICA_CHICAGO', 'AMERICA_DENVER', 'AMERICA_LOS_ANGELES', name='timezone_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clients_id'), 'clients', ['id'], unique=False)
    op.create_index(op.f('ix_clients_telegram_id'), 'clients', ['telegram_id'], unique=True)
    op.create_table('masters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('work_days', postgresql.ARRAY(sa.Integer()), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('slot_size_min', sa.Integer(), nullable=False),
    sa.Column('timezone', postgresql.ENUM('EUROPE_MINSK', 'EUROPE_MOSCOW', 'EUROPE_KIEV', 'EUROPE_WARSAW', 'EUROPE_VILNIUS', 'EUROPE_RIGA', 'EUROPE_TALLINN', 'EUROPE_BUCHAREST', 'EUROPE_CHISINAU', 'ASIA_YEREVAN', 'ASIA_TBILISI', 'ASIA_ALMATY', 'ASIA_BISHKEK', 'ASIA_TASHKENT', 'EUROPE_LONDON', 'EUROPE_PARIS', 'EUROPE_BERLIN', 'EUROPE_ROME', 'EUROPE_MADRID', 'EUROPE_AMSTERDAM', 'AMERICA_NEW_YORK', 'AMERICA_CHICAGO', 'AMERICA_DENVER', 'AMERICA_LOS_ANGELES', name='timezone_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_masters_id'), 'masters', ['id'], unique=False)
    op.create_index(op.f('ix_masters_telegram_id'), 'masters', ['telegram_id'], unique=True)
    op.create_table('bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('master_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_min', sa.Integer(), nullable=False),
    sa.Column('status', postgresql.ENUM('PENDING', 'CONFIRMED', 'DECLINED', 'CANCELLED', name='booking_status_enum'), nullable=False),
    sa.Column('attendance_outcome', postgresql.ENUM('UNKNOWN', 'ATTENDED', 'NO_SHOW', name='attendance_outcome_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['master_id'], ['masters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_bookings_master_start_at', 'bookings', ['master_id', 'start_at'], unique=False)
    op.create_index('ix_bookings_master_status_start_at', 'bookings', ['master_id', 'status', 'start_at'], unique=False)
    op.create_table('invites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=32), nullable=False),
    sa.Column('type', postgresql.ENUM('MASTER', 'CLIENT', name='invite_type_enum'), nullable=False),
    sa.Column('max_uses', sa.SmallInteger(), nullable=True),
    sa.Column('used_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('master_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['master_id'], ['masters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invites_token'), 'invites', ['token'], unique=True)
    op.create_table('master_clients',
    sa.Column('master_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['master_id'], ['masters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('master_id', 'client_id')
    )
    op.create_table('subscriptions',
    sa.Column('master_id', sa.Integer(), nullable=False),
    sa.Column('plan', postgresql.ENUM('FREE', 'PRO', name='subscription_plan_enum'), nullable=False),
    sa.Column('trial_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paid_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['master_id'], ['masters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('master_id')
    )
    op.create_table('workday_overrides',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('master_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.ForeignKeyConstraint(['master_id'], ['masters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('master_id', 'date', name='uq_override_master_date')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workday_overrides')
    op.drop_table('subscriptions')
    op.drop_table('master_clients')
    op.drop_index(op.f('ix_invites_token'), table_name='invites')
    op.drop_table('invites')
    op.drop_index('ix_bookings_master_status_start_at', table_name='bookings')
    op.drop_index('ix_bookings_master_start_at', table_name='bookings')
    op.drop_table('bookings')
    op.drop_index(op.f('ix_masters_telegram_id'), table_name='masters')
    op.drop_index(op.f('ix_masters_id'), table_name='masters')
    op.drop_table('masters')
    op.drop_index(op.f('ix_clients_telegram_id'), table_name='clients')
    op.drop_index(op.f('ix_clients_id'), table_name='clients')
    op.drop_table('clients')
    # ### end Alembic commands ###
